#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "--------- dev-env ---------"

cd $script_dir

# Copies dir contents at the leaf level
copy_dir() {
    pushd $1
    to=$2

    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        name=$(basename "$dir")   # removes ./ prefix safely
        execute rm -rf "$to/$name"
        execute cp -r "$dir" "$to/$name"
    done
    popd
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $to/$name 
    execute cp $from $to/$name
}

copy_dir env/.config $HOME/.config

copy_file env/.wezterm.lua $HOME
copy_file env/.zshrc $HOME

# Copy karabiner from config to env
# copy_file $HOME/.config/karabiner/karabiner.json env/.config/karabiner


